version: '3.6'
services:
  server:
    build: '.'
    volumes:
      - .:/go/src/github.com/user/go-gopher/backend
  nginx:
    build: './nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - 'server'
