version: '3.6'

services:
  server:
    build: '.'
    volumes:
      - .:/go/src/github.com/AlexMin314/go-gopher/backend
    depends_on:
      - 'mongo'
    links:
      - mongo
    networks:
      - backend
  nginx:
    build: './nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - 'server'
      - 'mongo'
    networks:
      - backend
  mongo:
    image: mongo:latest
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    # volumes:
    #   - type: bind
    #     source: ./backup
    #     target: /backup
    networks:
      - backend

networks:
  frontend:
  backend:
